// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEOn9RHjw2zvfyFcPg6iHaNFlr509Cf5M',
    appId: '1:366878131351:web:281310f7e1a05d72b255d2',
    messagingSenderId: '366878131351',
    projectId: 'j-factory',
    authDomain: 'j-factory.firebaseapp.com',
    storageBucket: 'j-factory.firebasestorage.app',
    measurementId: 'G-WJJR2X6P4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHWWFg_Jah3XfL-_3FqN3O9DOJkFs5dyA',
    appId: '1:366878131351:android:cef8649585fb60acb255d2',
    messagingSenderId: '366878131351',
    projectId: 'j-factory',
    storageBucket: 'j-factory.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZepDx15bJeN7WeWClaNfj04eCxaTJADc',
    appId: '1:366878131351:ios:cc41085b59a7c48fb255d2',
    messagingSenderId: '366878131351',
    projectId: 'j-factory',
    storageBucket: 'j-factory.firebasestorage.app',
    iosClientId: '366878131351-46urmtc7i16c480febug5n4oreu8uhn3.apps.googleusercontent.com',
    iosBundleId: 'com.example.vendorAds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZepDx15bJeN7WeWClaNfj04eCxaTJADc',
    appId: '1:366878131351:ios:cc41085b59a7c48fb255d2',
    messagingSenderId: '366878131351',
    projectId: 'j-factory',
    storageBucket: 'j-factory.firebasestorage.app',
    iosClientId: '366878131351-46urmtc7i16c480febug5n4oreu8uhn3.apps.googleusercontent.com',
    iosBundleId: 'com.example.vendorAds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEOn9RHjw2zvfyFcPg6iHaNFlr509Cf5M',
    appId: '1:366878131351:web:058ba8cb0d3c36cab255d2',
    messagingSenderId: '366878131351',
    projectId: 'j-factory',
    authDomain: 'j-factory.firebaseapp.com',
    storageBucket: 'j-factory.firebasestorage.app',
    measurementId: 'G-0N28TK214C',
  );
}
