// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFYUY93SUSMC7ZD9fhsH4YFFOs-3cl-vo',
    appId: '1:468556282634:web:a8c16384daad9e3406d8f3',
    messagingSenderId: '468556282634',
    projectId: 'fir-test-96091',
    authDomain: 'fir-test-96091.firebaseapp.com',
    storageBucket: 'fir-test-96091.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFYUY93SUSMC7ZD9fhsH4YFFOs-3cl-vo',
    appId: '1:468556282634:android:1ecea6bdd9bdd90806d8f3',
    messagingSenderId: '468556282634',
    projectId: 'fir-test-96091',
    storageBucket: 'fir-test-96091.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD6FyTTLFGtW92jr1ub1grKnRXJuvCrSM',
    appId: '1:468556282634:ios:4a92340971f2b53006d8f3',
    messagingSenderId: '468556282634',
    projectId: 'fir-test-96091',
    storageBucket: 'fir-test-96091.firebasestorage.app',
    iosClientId: '468556282634-facu5f56ck3aqrb0egga34b5up3o6ata.apps.googleusercontent.com',
    iosBundleId: 'vendor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD6FyTTLFGtW92jr1ub1grKnRXJuvCrSM',
    appId: '1:468556282634:ios:4a92340971f2b53006d8f3',
    messagingSenderId: '468556282634',
    projectId: 'fir-test-96091',
    storageBucket: 'fir-test-96091.firebasestorage.app',
    iosClientId: '468556282634-facu5f56ck3aqrb0egga34b5up3o6ata.apps.googleusercontent.com',
    iosBundleId: 'vendor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFYUY93SUSMC7ZD9fhsH4YFFOs-3cl-vo',
    appId: '1:468556282634:web:a8c16384daad9e3406d8f3',
    messagingSenderId: '468556282634',
    projectId: 'fir-test-96091',
    authDomain: 'fir-test-96091.firebaseapp.com',
    storageBucket: 'fir-test-96091.firebasestorage.app',
  );
}
